version: '3.7'

services:
  redis:
    container_name: redis
    image: redis:6
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    container_name: postgres
    image: postgres:13.1-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  back:
volumes:
  pgdata:
  redis-data:
  pgadmin-data:
  redis_insight-data:
  mongodata: