name: Deploy to server

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: Install Node.js
      uses: actions/setup-node@v2.5.0
    - name: Install npm dependencies
      run: npm i
    - name: Run build task
      run: npm run build --if-present
    - name: SSH deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SECRET_KEY }} 
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        REMOTE_PORT: ${{ secrets.PORT }}
        TARGET: ${{ secrets.FOLDER }}
    - name: Run SSH command
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: pm2 restart Nidhoggbot
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        privateKey: ${{ secrets.SECRET_KEY }} 
