name: Deploy to server

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands using password
      uses: ./
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.FOLDER }}
          git checkout master && git pull
          npm run build
          pm2 restart Nidhoggbot
